/* 羊毛货架 · 资源数据
 * 字段：name 名称 / logo 图标路径 / color 标识色 / cat 分类
 *      desc 这是什么（含邀请码的卡片可留空） / perk 福利 / note 福利说明 / code 邀请码（无则留空）
 *      condition 使用限制 / tags 标签 / url / cta 按钮文案
 *      perkLabel 福利区标签（可选，默认「🎁 新用户福利」）
 *      featured 推荐（可选，卡片左上角显示金色「荐」徽标）
 *      offline 暂时下线（可选，true 时前台隐藏该卡片，仅在管理台可见）
 * 添加卡片请用 admin.html 可视化编辑器，导出后覆盖本文件即可
 */
window.PERKS = [
  {
    "id": "atria",
    "name": "Atria API",
    "logo": "assets/atria.png",
    "color": "#4338ca",
    "cat": "国产模型",
    "desc": "国产全新模型 API 服务，各类指标均位居前列。",
    "perk": "注册即送 1 亿 Token",
    "note": "进群反馈问题，额度耗尽可申请补充。",
    "code": "",
    "condition": "且薅且珍惜",
    "tags": ["API", "国产模型", "邮箱注册"],
    "url": "https://api.atria-asi.ai",
    "cta": "立即领取",
    "featured": true
  },
  {
    "id": "intern",
    "name": "端硕 Discovery",
    "logo": "assets/intern-discovery.svg",
    "color": "#0f766e",
    "cat": "国产模型",
    "desc": "国产模型推理服务平台，支持大部分主流国产模型。",
    "perk": "7 天共 10 亿 Token",
    "note": "每 5 小时重置 2 亿，7 天共 10 亿 Token。",
    "code": "",
    "condition": "免费额度 · 每 5 小时重置",
    "tags": ["API", "国产模型", "邮箱注册"],
    "url": "https://discovery.intern-ai.org.cn/",
    "cta": "立即领取",
    "featured": true
  },
  {
    "id": "workbuddy",
    "name": "WorkBuddy",
    "logo": "assets/workbuddy.png",
    "color": "#0d9488",
    "cat": "官方应用",
    "desc": "国际版 WorkBuddy，国外各种大模型，每天签到即可获得积分。",
    "perk": "邀请双方均获奖励",
    "note": "通过邀请链接注册，邀请人与被邀请人都有奖励。",
    "code": "EZFLGCH3",
    "condition": "限新用户 · 奖励以官网政策为准",
    "tags": ["官方应用", "邀请有礼", "每日签到"],
    "url": "https://workbuddy.ai/invite?code=EZFLGCH3",
    "cta": "立即领取",
    "featured": true
  },
  {
    "id": "agentrouter",
    "name": "AgentRouter",
    "logo": "assets/agentrouter.ico",
    "color": "#0d9488",
    "cat": "公益中转",
    "desc": "知名老牌公益站，羊毛党的福音。",
    "perk": "$175 额度",
    "note": "注册 $100 + 链接 $50 + 签到 $25 = $175。",
    "code": "D9TZ",
    "condition": "限新用户 · 额度以官网政策为准",
    "tags": ["公益中转", "GitHub", "Linux do"],
    "url": "https://agentrouter.org/register?aff=D9TZ",
    "cta": "立即领取",
    "featured": true
  },
  {
    "id": "cctq",
    "name": "CCTQ",
    "logo": "assets/cctq.png",
    "color": "#ea580c",
    "cat": "付费中转",
    "desc": "价格实惠经济耐用，支持无理由退款。",
    "perk": "额度耐用 · 价格实惠",
    "note": "不送额度，单价低、用得久。",
    "code": "8Tzn",
    "condition": "付费中转 · 可开发票",
    "tags": ["付费中转", "无注册限制"],
    "url": "https://www.cctq.ai/sign-up?aff=8Tzn",
    "cta": "查看福利",
    "perkLabel": "💡 站点特色",
    "featured": true
  },
  {
    "id": "anyrouter",
    "name": "AnyRouter",
    "logo": "assets/agentrouter.ico",
    "color": "#7c3aed",
    "cat": "公益中转",
    "desc": "运营已久的公益老站，稳定可靠，速度较慢。",
    "perk": "$125 额度",
    "note": "注册 $50 + 链接 $50 + 签到 $25 = $125。",
    "code": "ziut",
    "condition": "限新用户 · 速度较慢",
    "tags": ["公益中转", "Linux do", "教育邮箱"],
    "url": "https://anyrouter.top/register?aff=ziut",
    "cta": "立即领取"
  },
  {
    "id": "codego",
    "name": "Code Go",
    "logo": "assets/codego.png",
    "color": "#f06738",
    "cat": "付费中转",
    "desc": "面向长期 AI Coding 的统一入口，支持 Codex、Claude Code 中转。",
    "perk": "统一入口 · 多模型中转",
    "note": "覆盖 Codex API、Claude Code API，含免费模型与模型广场。",
    "code": "GTIL",
    "condition": "付费中转 · 注册即用",
    "tags": ["付费中转", "无注册限制", "多模型"],
    "url": "https://shu26.cfd/sign-up?aff=GTIL",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "docode",
    "name": "DoCode",
    "logo": "assets/docode.ico",
    "color": "#db2777",
    "cat": "付费中转",
    "desc": "VIP 制，多模型分组，模型数量丰富，VIP 等级越高倍率越低。",
    "perk": "$300 体验额度",
    "note": "注册即赠，消耗较快；VIP 每日可抽奖 3+ 次。",
    "code": "JFL6",
    "condition": "付费中转 · 可开发票",
    "tags": ["付费中转", "无注册限制", "VIP 签到"],
    "url": "https://docode.cc/register?aff=JFL6",
    "cta": "去薅一下"
  },
  {
    "id": "bananapro",
    "name": "Nano Banana Pro",
    "logo": "assets/bananapro.ico",
    "color": "#eab308",
    "cat": "国产模型",
    "desc": "",
    "perk": "注册送 18 积分",
    "note": "注册送 18 积分，填邀请码再赠 12 积分。",
    "code": "U666",
    "condition": "积分制 · 用完需付费充值",
    "tags": ["国产模型", "多模型", "按量付费"],
    "url": "https://www.bananapro.site?ref=U666",
    "cta": "立即领取"
  },
  {
    "id": "l0veyou",
    "name": "l0veyou",
    "logo": "assets/l0veyou.svg",
    "color": "#ec4899",
    "cat": "公益中转",
    "desc": "Linux Do 社区佬搭建的公益生图站，主打简单好用。",
    "perk": "永久免费 1K 分辨率",
    "note": "1K 永久免费，更高分辨率耗积分。",
    "code": "",
    "condition": "公益站点 · 请勿滥用",
    "tags": ["公益中转", "免费", "Linux do"],
    "url": "https://l0veyou.com",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "lingguang",
    "name": "灵光AI",
    "logo": "assets/lingguang.png",
    "color": "#7c3aed",
    "cat": "国产模型",
    "desc": "蚂蚁集团旗下的全模态免费 AI 应用，集成对话、生图等能力。",
    "perk": "全模态免费使用",
    "note": "对话、生图等能力全部免费。",
    "code": "",
    "condition": "免费 · 需注册账号",
    "tags": ["国产模型", "免费", "全模态"],
    "url": "https://www.lingguang.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "elevenlabs",
    "name": "ElevenLabs",
    "logo": "assets/elevenlabs.svg",
    "color": "#0f172a",
    "cat": "官方应用",
    "desc": "强大的 AI 音乐、音效与语音生成平台，效果自然逼真。",
    "perk": "新用户 10000 积分",
    "note": "注册送 10000 积分，可生成语音、音效、音乐。",
    "code": "",
    "condition": "积分制 · 高级功能需订阅",
    "tags": ["API", "官方应用", "语音", "音乐", "音效"],
    "url": "https://try.elevenlabs.io/fdv27inzunb5",
    "cta": "立即领取"
  },
  {
    "id": "100font",
    "name": "100font",
    "logo": "assets/100font.png",
    "color": "#ca9d01",
    "cat": "设计工具",
    "desc": "免费商用字体下载站，支持分类检索与在线预览。",
    "perk": "字体全部免费商用",
    "note": "含安装教程与打包合集，商用零成本。",
    "code": "",
    "condition": "免费 · 部分付费字体专区",
    "tags": ["免费", "字体", "商用授权"],
    "url": "https://www.100font.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "docsmall",
    "name": "docsmall",
    "logo": "assets/docsmall.png",
    "color": "#666666",
    "cat": "设计工具",
    "desc": "在线图片、GIF 与 PDF 处理工具，含 AI 抠图。",
    "perk": "压缩 · 抠图 · 格式转换",
    "note": "图片高清化、裁剪、分割，PDF 合并转换全免费。",
    "code": "",
    "condition": "免费 · 在线即用",
    "tags": ["免费", "图片处理", "PDF"],
    "url": "https://docsmall.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "lddgo",
    "name": "LDDGO",
    "logo": "assets/lddgo.png",
    "color": "#019588",
    "cat": "在线工具",
    "desc": "收录 400+ 个在线小工具的工具箱大全。",
    "perk": "418 个工具免费用",
    "note": "字符处理、格式转换、加密解密、坐标换算应有尽有。",
    "code": "",
    "condition": "免费 · 在线即用",
    "tags": ["免费", "工具箱", "格式转换"],
    "url": "https://www.lddgo.net/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "drawio",
    "name": "draw.io",
    "logo": "assets/drawio.ico",
    "color": "#f08705",
    "cat": "在线工具",
    "desc": "免费在线图表绘制工具，流程图、UML 一把梭。",
    "perk": "完全免费 · 免注册",
    "note": "支持导入 Visio、Gliffy、Lucidchart 文件。",
    "code": "",
    "condition": "免费 · 免注册直接用",
    "tags": ["免费", "画图", "免注册"],
    "url": "https://app.diagrams.net/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "bitbug",
    "name": "比特虫",
    "logo": "assets/bitbug.png",
    "color": "#5b8a6b",
    "cat": "在线工具",
    "desc": "在线生成网站 favicon.ico 图标的小工具。",
    "perk": "一键生成 ico 图标",
    "note": "上传图片自动生成多尺寸 ico，附引用代码。",
    "code": "",
    "condition": "免费 · 限 500K 内图片",
    "tags": ["免费", "ICO 生成", "开发者"],
    "url": "https://www.bitbug.net/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "zhaotaici",
    "name": "找台词",
    "logo": "assets/zhaotaici.png",
    "color": "#ed7581",
    "cat": "影视资源",
    "desc": "影视台词搜索，按片名、导演、年份精准找台词。",
    "perk": "台词搜索 · 字幕提取",
    "note": "支持根据台词反搜场景片段，可在线收藏。",
    "code": "",
    "condition": "免费 · 部分功能需会员",
    "tags": ["免费", "台词搜索", "影视"],
    "url": "https://www.zhaotaici.cn/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  }
];
