/* 羊毛货架 · 资源数据
 * 字段：name 名称 / logo 图标路径 / color 标识色 / cat 分类
 *      desc 这是什么（含邀请码的卡片可留空） / perk 福利 / note 福利说明 / code 邀请码（无则留空）
 *      condition 使用限制 / tags 标签 / url / cta 按钮文案
 *      perkLabel 福利区标签（可选，默认「🎁 新用户福利」）
 *      featured 推荐（可选，卡片左上角显示金色「荐」徽标）
 *      offline 暂时下线（可选，true 时前台隐藏该卡片，仅在管理台可见）
 * 添加卡片请用 admin.html 可视化编辑器，导出后覆盖本文件即可
 */
window.PERKS = [
  {
    "id": "atria",
    "name": "Atria API",
    "logo": "assets/atria.png",
    "color": "#4338ca",
    "cat": "国产模型",
    "desc": "国产全新模型 API 服务，各类指标均位居前列。",
    "perk": "注册即送 1 亿 Token",
    "note": "进群反馈问题，额度耗尽可申请补充。",
    "code": "",
    "condition": "免费额度 · 额度耗尽可申请补充",
    "tags": ["API", "国产模型", "邮箱注册"],
    "url": "https://api.atria-asi.ai",
    "cta": "立即领取",
    "featured": true
  },
  {
    "id": "ykkk",
    "name": "YKKK机场",
    "logo": "assets/ykkk.jpg",
    "color": "#2563eb",
    "cat": "机场服务",
    "desc": "科学上网高质量机场，线路与体验以官网实际情况为准。",
    "perk": "高质量机场服务",
    "note": "通过专属链接注册，套餐与活动以官网页面为准。",
    "code": "JdHGgSqo",
    "condition": "服务内容、套餐与使用规则以官网为准",
    "tags": ["机场服务", "科学上网", "邀请有礼"],
    "url": "https://panel.ykkk.best/#/register?code=JdHGgSqo",
    "cta": "立即注册",
    "featured": true
  },
  {
    "id": "workbuddy",
    "name": "WorkBuddy 国际版",
    "logo": "assets/workbuddy.png",
    "color": "#0d9488",
    "cat": "官方应用",
    "desc": "国际版 WorkBuddy，聚合国外各种大模型，每天签到即可获得积分。",
    "perk": "DeepSeek 4.1 Flash 免费",
    "note": "免费额度，速速来薅；通过邀请链接注册，邀请人与被邀请人都有奖励。",
    "code": "EZFLGCH3",
    "condition": "限新用户 · 奖励以官网政策为准",
    "tags": ["官方应用", "邀请有礼", "每日签到"],
    "url": "https://workbuddy.ai/invite?code=EZFLGCH3",
    "cta": "立即领取"
  },
  {
    "id": "agentrouter",
    "name": "AgentRouter",
    "logo": "assets/agentrouter.ico",
    "color": "#0d9488",
    "cat": "公益中转",
    "desc": "知名老牌公益站，羊毛党的福音，注册需符合条件的账号。",
    "perk": "$175 额度",
    "note": "注册 $100 + 链接 $50 + 签到 $25 = $175。",
    "code": "D9TZ",
    "condition": "仅限 2025 年 12 月前注册的 GitHub 账号，或 LinuxDo 0 级以上用户",
    "tags": ["公益中转", "GitHub", "Linux do"],
    "url": "https://agentrouter.org/register?aff=D9TZ",
    "cta": "立即领取",
    "featured": true
  },
  {
    "id": "jiji",
    "name": "JiJi API",
    "logo": "assets/jiji.png",
    "color": "#ce6b45",
    "cat": "付费中转",
    "desc": "面向 Codex、Claude Code 的付费中转，兼容 OpenAI 与 Anthropic 协议，换 Base URL 即用。",
    "perk": "GPT、Grok 倍率低至 0.19x",
    "note": "充值 1:1 到账、0 手续费，1 元起充；稳定分组倍率低至 0.19x，按实际用量计费。",
    "code": "DDS6C3C6PE5G",
    "condition": "付费中转 · 价格以官网分组为准",
    "tags": ["付费中转", "多模型", "无注册限制"],
    "url": "https://www.jiji.cc/register?aff=DDS6C3C6PE5G",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色",
    "featured": true
  },
  {
    "id": "mcgrox",
    "name": "Grox",
    "logo": "assets/mcgrox.png",
    "color": "#3875f6",
    "cat": "付费中转",
    "desc": "一个 Key 调用多模型的 API 中转，覆盖 Claude、GPT、Gemini、Antigravity，智能路由自动故障转移。",
    "perk": "填邀请码 · 进群送日卡",
    "note": "注册填写邀请码，进群绑定邮箱即送日卡；支持订阅与按量两种计费。",
    "code": "FZJVH4YKBDP9",
    "condition": "付费中转 · 日卡以官网/群内政策为准",
    "tags": ["付费中转", "多模型", "邀请有礼"],
    "url": "https://www.mcgrox.top/register?aff=FZJVH4YKBDP9",
    "cta": "去薅一下",
    "perkLabel": "🎁 新用户福利",
    "featured": true
  },
  {
    "id": "flatrouter",
    "name": "FlatRouter",
    "logo": "assets/flatrouter.png",
    "color": "#2563eb",
    "cat": "付费中转",
    "desc": "GPT 专线付费中转，官方兼容协议，改一个 base_url 即可迁移 Codex、Cursor 等客户端。",
    "perk": "新人订阅仅需 19.9 元",
    "note": "月付低至 19.9 元，按官方模型价 × 平台系数计费，实付约为官方价的一折。",
    "code": "LCWLFBYCS79D",
    "condition": "付费订阅 · 具体档位以官网为准",
    "tags": ["付费中转", "GPT", "订阅制"],
    "url": "https://flatrouter.com/register?ref=LCWLFBYCS79D",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色",
    "featured": true
  },
  {
    "id": "ilovetoken",
    "name": "Love Token",
    "logo": "assets/ilovetoken.png",
    "color": "#7c3aed",
    "cat": "付费中转",
    "desc": "一个 Key 调用多模型的 API 网关，覆盖 GPT、Claude、Gemini，支持按量与订阅两种计费。",
    "perk": "GPT 倍率较低",
    "note": "换 Key 与 Base URL 即可迁移，价格随模型与上游浮动，实时价见控制台。",
    "code": "B5HQQS4S4VRR",
    "condition": "付费中转 · 实时价以官网为准",
    "tags": ["付费中转", "多模型", "GPT"],
    "url": "https://ilovetoken.top/register?aff=B5HQQS4S4VRR",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "zerocat",
    "name": "ZeroCat",
    "logo": "assets/zerocat.png",
    "color": "#fd5300",
    "cat": "付费中转",
    "desc": "分组丰富的付费中转，覆盖 GPT、Claude 与国产模型，按次计费。",
    "perk": "特惠分组 · 单价实惠",
    "note": "设有特惠分组，按次计费更划算；支持每日签到领取额度。",
    "code": "",
    "condition": "付费中转 · 价格以官网分组为准",
    "tags": ["付费中转", "多模型", "每日签到"],
    "url": "https://zero.cat/sign-up?aff=8Otd",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "monkeycode",
    "name": "MonkeyCode",
    "logo": "assets/monkeycode.png",
    "color": "#0a9c69",
    "cat": "开发平台",
    "desc": "浏览器里就能用的 AI 开发平台，任务跑在云端环境中。",
    "perk": "每日 1000 万 Token 免费额度",
    "note": "免费套餐长期可用，含 1C/4G 云端开发环境与基础模型；每日签到送 100 积分，邀好友送 5000 积分。",
    "code": "",
    "condition": "免费套餐长期可用 · 注册即用，无需安装",
    "tags": ["免费", "云服务", "每日签到"],
    "url": "https://monkeycode-ai.com/?ic=01a0b561-e739-7b34-9f8b-d36f4944da62",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "intern",
    "name": "端硕 Discovery",
    "logo": "assets/intern-discovery.svg",
    "color": "#0f766e",
    "cat": "国产模型",
    "desc": "国产模型推理服务平台，支持大部分主流国产模型。",
    "perk": "注册即送 2 亿 Token",
    "note": "额度按月重置，每月 2 亿。",
    "code": "",
    "condition": "免费额度 · 每月重置",
    "tags": ["API", "国产模型", "邮箱注册"],
    "url": "https://discovery.intern-ai.org.cn/",
    "cta": "立即领取"
  },
  {
    "id": "anyrouter",
    "name": "AnyRouter",
    "logo": "assets/anyrouter.png",
    "color": "#7c3aed",
    "cat": "公益中转",
    "desc": "运营已久的公益老站，稳定可靠，速度较慢，注册有邮箱或社区等级限制。",
    "perk": "$125 额度",
    "note": "注册 $50 + 链接 $50 + 签到 $25 = $125。",
    "code": "ZKIC",
    "condition": "仅限教育邮箱，或 LinuxDo 2 级以上用户",
    "tags": ["公益中转", "Linux do", "教育邮箱"],
    "url": "https://anyrouter.top/register?aff=ZKIC",
    "cta": "立即领取"
  },
  {
    "id": "docode",
    "name": "DoCode",
    "logo": "assets/docode.png",
    "color": "#db2777",
    "cat": "付费中转",
    "desc": "VIP 制，多模型分组，模型数量丰富，VIP 等级越高倍率越低。",
    "perk": "$300 体验额度",
    "note": "注册即赠，消耗较快；VIP 每日可抽奖 3+ 次。",
    "code": "JFL6",
    "condition": "付费中转 · 可开发票",
    "tags": ["付费中转", "无注册限制", "VIP 签到"],
    "url": "https://docode.cc/register?aff=JFL6",
    "cta": "去薅一下"
  },
  {
    "id": "bananapro",
    "name": "Nano Banana Pro",
    "logo": "assets/bananapro.ico",
    "color": "#eab308",
    "cat": "AI 创作",
    "desc": "多模型 AI 生图平台，用对话就能生成和修改图片。",
    "perk": "注册送 18 积分",
    "note": "站内汇集 Nano Banana、GPT Image、Seedream、Qwen Image 等多个系列模型。",
    "code": "U666",
    "condition": "积分制 · 用完需付费充值",
    "tags": ["AI 生图", "多模型", "按量付费"],
    "url": "https://www.bananapro.site?ref=U666",
    "cta": "立即领取"
  },
  {
    "id": "seedeo",
    "name": "Seedeo",
    "logo": "assets/seedeo.png",
    "color": "#7ed321",
    "cat": "AI 创作",
    "desc": "AI 图像与视频创作平台，支持文生图、文生视频与配音配乐。",
    "perk": "邀请双方各得 40 积分",
    "note": "好友通过专属链接注册或完成首次购买后自动发放，邀请人与被邀请人都有奖励。",
    "code": "",
    "condition": "注册可用 · 奖励以官网规则为准",
    "tags": ["AI 生图", "视频", "语音"],
    "url": "https://seedeo.ai/invite/922833EB",
    "cta": "去薅一下",
    "perkLabel": "🎁 新用户福利"
  },
  {
    "id": "pixai",
    "name": "PixAI",
    "logo": "assets/pixai.png",
    "color": "#111827",
    "cat": "AI 创作",
    "desc": "AI 动漫绘画平台，支持角色、OC 与 VTuber 形象生成。",
    "perk": "注册送 2000 积分",
    "note": "每日签到再送 10000 积分，可用于生成动漫风格图片。",
    "code": "",
    "condition": "注册可用 · 积分以官网规则为准",
    "tags": ["AI 生图", "动漫", "免费"],
    "url": "https://pixai.art/referral?refCode=XXAC9YP3&utm_source=referral",
    "cta": "去薅一下",
    "perkLabel": "🎁 新用户福利"
  },
  {
    "id": "kitt",
    "name": "KITT",
    "logo": "assets/kitt.png",
    "color": "#f97316",
    "cat": "开发平台",
    "desc": "面向开发者的 AI 工程化平台，提供可观测、可审阅、可调度的应用底座。",
    "perk": "首次使用可得 200 万 Token",
    "note": "需通过专属链接在官网登录/注册，完成首次有效使用后发放；直接在客户端注册不计入。",
    "code": "",
    "condition": "需注册 · 专属链接注册并完成首次使用方计入",
    "tags": ["开发者", "AI 应用"],
    "url": "https://kitt.plus/?invite=7D8CFX29#activity",
    "cta": "去薅一下",
    "perkLabel": "🎁 新用户福利"
  },
  {
    "id": "qiniu",
    "name": "七牛云",
    "logo": "assets/qiniu.png",
    "color": "#0aa5e8",
    "cat": "开发平台",
    "desc": "国内云服务商，提供对象存储、CDN、云服务器与大模型推理。",
    "perk": "新客对象存储低至 1 折",
    "note": "另有 0 元试用大模型、海外 CDN 流量立减等活动。",
    "code": "",
    "condition": "需实名注册 · 优惠以官网活动页为准",
    "tags": ["新客优惠", "云服务", "对象存储"],
    "url": "https://s.qiniu.com/aYFJvy",
    "cta": "去薅一下",
    "perkLabel": "🎁 新用户福利"
  },
  {
    "id": "lingguang",
    "name": "灵光AI",
    "logo": "assets/lingguang.png",
    "color": "#7c3aed",
    "cat": "国产模型",
    "desc": "蚂蚁集团旗下的全模态免费 AI 应用，集成对话、生图等能力。",
    "perk": "全模态免费使用",
    "note": "对话、生图等能力全部免费。",
    "code": "",
    "condition": "免费 · 需注册账号",
    "tags": ["国产模型", "免费", "全模态"],
    "url": "https://www.lingguang.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "firefly",
    "name": "Adobe Firefly",
    "logo": "assets/firefly.png",
    "color": "#e8442a",
    "cat": "AI 创作",
    "desc": "Adobe 的 AI 创作平台，用文字生成图像、视频、音频与矢量图。",
    "perk": "免费每日生成额度",
    "note": "集成 30+ AI 模型，覆盖图像、视频、音频、矢量等生成类型。",
    "code": "",
    "condition": "需 Adobe 账号 · 免费用户每日有生成额度",
    "tags": ["AI 生图", "视频", "音频"],
    "url": "https://firefly.adobe.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "magnific",
    "name": "Magnific",
    "logo": "assets/magnific.png",
    "color": "#111827",
    "cat": "AI 创作",
    "desc": "AI 图像放大与增强工具，提升分辨率并补充画面细节。",
    "perk": "AI 画质增强",
    "note": "面向插画、摄影与设计稿的细节重绘，支持风格与强度调节。",
    "code": "",
    "condition": "订阅制 · 具体额度以官网为准",
    "tags": ["图片", "订阅制"],
    "url": "https://www.magnific.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "xjbh",
    "name": "瞎几把画",
    "logo": "assets/xjbh.svg",
    "color": "#2c3e50",
    "cat": "AI 创作",
    "desc": "基于 GPT Image 2.5 的 AI 绘画站，写下描述即可出图。",
    "perk": "GPT Image 2.5 绘画",
    "note": "绘画走 gpt-image-2.5，另提供 gpt-5.5 系列模型可对话使用。",
    "code": "",
    "condition": "需 Linux DO 授权登录 · 首次使用需绑定邮箱",
    "tags": ["AI 生图", "Linux do", "免费"],
    "url": "https://xjbh.lol/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "l0veyou",
    "name": "l0veyou",
    "logo": "assets/l0veyou.svg",
    "color": "#ec4899",
    "cat": "公益中转",
    "desc": "Linux Do 社区佬搭建的公益生图站，主打简单好用。",
    "perk": "永久免费 1K 分辨率",
    "note": "1K 永久免费，更高分辨率耗积分。",
    "code": "",
    "condition": "公益站点 · 请勿滥用",
    "tags": ["公益中转", "免费", "Linux do"],
    "url": "https://l0veyou.com",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "elevenlabs",
    "name": "ElevenLabs",
    "logo": "assets/elevenlabs.svg",
    "color": "#0f172a",
    "cat": "官方应用",
    "desc": "强大的 AI 音乐、音效与语音生成平台，效果自然逼真。",
    "perk": "新用户 10000 积分",
    "note": "注册送 10000 积分，可生成语音、音效、音乐。",
    "code": "",
    "condition": "积分制 · 高级功能需订阅",
    "tags": ["API", "官方应用", "语音", "音乐", "音效"],
    "url": "https://try.elevenlabs.io/fdv27inzunb5",
    "cta": "立即领取"
  },
  {
    "id": "docsmall",
    "name": "docsmall",
    "logo": "assets/docsmall.png",
    "color": "#666666",
    "cat": "设计工具",
    "desc": "在线图片、GIF 与 PDF 处理工具，含 AI 抠图。",
    "perk": "压缩 · 抠图 · 格式转换",
    "note": "图片高清化、裁剪、分割，PDF 合并转换全免费。",
    "code": "",
    "condition": "免费 · 在线即用",
    "tags": ["免费", "图片处理", "PDF"],
    "url": "https://docsmall.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "100font",
    "name": "100font",
    "logo": "assets/100font.png",
    "color": "#ca9d01",
    "cat": "设计工具",
    "desc": "免费商用字体下载站，支持分类检索与在线预览。",
    "perk": "字体全部免费商用",
    "note": "含安装教程与打包合集，商用零成本。",
    "code": "",
    "condition": "免费 · 部分付费字体专区",
    "tags": ["免费", "字体", "商用授权"],
    "url": "https://www.100font.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "pixabay",
    "name": "Pixabay",
    "logo": "assets/pixabay.png",
    "color": "#4ca84c",
    "cat": "素材库",
    "desc": "免版税素材库，图片、插画、视频、音乐、音效一站齐全。",
    "perk": "630 万+ 免费素材",
    "note": "支持中文界面检索，素材可直接下载用于商业项目。",
    "code": "",
    "condition": "免费可商用 · 无需署名",
    "tags": ["免费", "图片", "视频", "商用授权"],
    "url": "https://pixabay.com/zh/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "mixkit",
    "name": "Mixkit",
    "logo": "assets/mixkit.png",
    "color": "#1f2937",
    "cat": "素材库",
    "desc": "免费商用素材站，提供视频、音乐、音效与剪辑模板。",
    "perk": "免费可商用素材",
    "note": "含 4 万余条视频、千余首音乐与三千多种音效，另有 PR/AE/FCP 模板。",
    "code": "",
    "condition": "免费可商用 · 无需署名与注册",
    "tags": ["免费", "视频", "音乐", "商用授权"],
    "url": "https://mixkit.co/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "kenney",
    "name": "Kenney",
    "logo": "assets/kenney.png",
    "color": "#3fbf9f",
    "cat": "素材库",
    "desc": "面向独立游戏开发的美术素材站，提供大量可直接使用的资源。",
    "perk": "数千套免费游戏素材",
    "note": "覆盖 2D 精灵图、3D 模型与音效，另附开源游戏入门套件。",
    "code": "",
    "condition": "CC0 公共领域 · 可商用 · 无需署名",
    "tags": ["免费", "游戏素材", "商用授权"],
    "url": "https://kenney.nl/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "productioncrate",
    "name": "ProductionCrate",
    "logo": "assets/productioncrate.png",
    "color": "#f06738",
    "cat": "素材库",
    "desc": "影视特效素材站，提供 VFX、动态图形与音效素材。",
    "perk": "免费 VFX 素材库",
    "note": "涵盖 HD/4K 特效、转场、背景、纹理与 AE 模板，另有 PRO 会员方案。",
    "code": "",
    "condition": "免费为主 · 部分素材需注册或 PRO 会员",
    "tags": ["免费", "特效", "视频", "音效"],
    "url": "https://footagecrate.productioncrate.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "sfxmint",
    "name": "SFXMint",
    "logo": "assets/sfxmint.png",
    "color": "#5b4de8",
    "cat": "素材库",
    "desc": "面向游戏、App 与视频的免费音效库，可描述搜索并在线试听。",
    "perk": "免费 CC0 音效",
    "note": "按 UI、打击、环境、卡通等分类整理，提供 WAV 与 MP3 两种格式。",
    "code": "",
    "condition": "CC0 公共领域 · 可商用 · 免注册免署名",
    "tags": ["免费", "音效", "商用授权"],
    "url": "https://sfxmint.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "freesoundorg",
    "name": "Freesound",
    "logo": "assets/freesound-org.png",
    "color": "#fd5b65",
    "cat": "素材库",
    "desc": "国际知名音效共享库，收录 73 万余条免费音效与录音素材。",
    "perk": "73 万+ 免费音效",
    "note": "覆盖音效、实地录音、循环片段与环境音，支持按标签与相似音检索。",
    "code": "",
    "condition": "免费 · 需注册登录后下载 · CC-BY 类素材商用需署名",
    "tags": ["免费", "音效", "需注册"],
    "url": "https://freesound.org",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "freesoundcn",
    "name": "FREESOUND 飞声",
    "logo": "assets/freesound-cn.png",
    "color": "#8119c9",
    "cat": "素材库",
    "desc": "国内无版权音乐库，主打可商用的 BGM 与剪辑配乐。",
    "perk": "免费可商用音乐",
    "note": "涵盖 BGM、配乐、音效等素材，可直接用于视频剪辑与商业项目。",
    "code": "",
    "condition": "免费可商用 · 具体授权范围以站内说明为准",
    "tags": ["免费", "音乐", "商用授权"],
    "url": "https://www.freesound.cn",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "drawio",
    "name": "draw.io",
    "logo": "assets/drawio.ico",
    "color": "#f08705",
    "cat": "在线工具",
    "desc": "免费在线图表绘制工具，流程图、UML 一把梭。",
    "perk": "完全免费 · 免注册",
    "note": "支持导入 Visio、Gliffy、Lucidchart 文件。",
    "code": "",
    "condition": "免费 · 免注册直接用",
    "tags": ["免费", "画图", "免注册"],
    "url": "https://app.diagrams.net/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "lddgo",
    "name": "LDDGO",
    "logo": "assets/lddgo.png",
    "color": "#019588",
    "cat": "在线工具",
    "desc": "收录 400+ 个在线小工具的工具箱大全。",
    "perk": "418 个工具免费用",
    "note": "字符处理、格式转换、加密解密、坐标换算应有尽有。",
    "code": "",
    "condition": "免费 · 在线即用",
    "tags": ["免费", "工具箱", "格式转换"],
    "url": "https://www.lddgo.net/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "bitbug",
    "name": "比特虫",
    "logo": "assets/bitbug.png",
    "color": "#5b8a6b",
    "cat": "在线工具",
    "desc": "在线生成网站 favicon.ico 图标的小工具。",
    "perk": "一键生成 ico 图标",
    "note": "上传图片自动生成多尺寸 ico，附引用代码。",
    "code": "",
    "condition": "免费 · 限 500K 内图片",
    "tags": ["免费", "ICO 生成", "开发者"],
    "url": "https://www.bitbug.net/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "zhaotaici",
    "name": "找台词",
    "logo": "assets/zhaotaici.png",
    "color": "#ed7581",
    "cat": "影视资源",
    "desc": "影视台词搜索，按片名、导演、年份精准找台词。",
    "perk": "台词搜索 · 字幕提取",
    "note": "支持根据台词反搜场景片段，可在线收藏。",
    "code": "",
    "condition": "免费 · 部分功能需会员",
    "tags": ["免费", "台词搜索", "影视"],
    "url": "https://www.zhaotaici.cn/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "agedm",
    "name": "AGE动漫",
    "logo": "assets/agedm.png",
    "color": "#7c5cc4",
    "cat": "影视资源",
    "desc": "动漫在线观看的聚合入口，按一周更新与排行榜浏览。",
    "perk": "在线观看 · 更新日历",
    "note": "提供番剧目录、一周放送表与排行榜，便于按更新节奏追番。",
    "code": "",
    "condition": "免费观看 · 站点仅提供页面服务，资源来自第三方",
    "tags": ["免费", "动漫", "影视"],
    "url": "https://www.agedm.io/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  },
  {
    "id": "ypojie",
    "name": "易破解",
    "logo": "assets/ypojie.png",
    "color": "#2b3a4a",
    "cat": "软件资源",
    "desc": "老牌绿色软件下载站，涵盖 Windows、macOS 与手机应用及系统教程。",
    "perk": "免费软件 · 每日更新",
    "note": "软件分类细致，含系统镜像、建站源码与图文教程。",
    "code": "",
    "condition": "免费 · 高速下载需签到获取积分",
    "tags": ["免费", "软件下载", "教程"],
    "url": "https://www.ypojie.com/",
    "cta": "去薅一下",
    "perkLabel": "💡 站点特色"
  }
];
